window:
  size: 168
  stride: 24
  filter: 1
split:
  idx_tr:
  - 1
  - 2
  - 3
  - 5
  - 7
  - 9
  - 13
  - 14
  idx_va:
  - 4
  - 8
  - 11
  idx_te:
  - 6
  - 10
  - 12
  - 15
model:
  rnn_unit: 64
  lstm_layers: 1
  input_size: 10
  output_size: 1
  dropout: 0.1
train:
  lr: 0.0005
  batch_size: 64
  max_epochs: 250
  max_grad_norm: 1.0
  patience: 30
  min_delta: 0.0001
data:
  feature_cols:
  - Temp_mean
  - Temp_std
  - Volt_std
  - Curr_abs_mean
  - Curr_rms
  - EFC_delta
  - EFC_max
  - Energy_cumulative
  - Energy_throughput
  - R_mean
  target_col:
  - SOH
paths:
  data_dir: data/features_1h_scaled
  parquet_pattern: df_FE_C{num:02d}_features_1h_scaled.parquet
